# coding: utf-8

"""
    Recomax REST API

    Recomax REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@recomax.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from .locale import Locale  # noqa: E501
from swagger_client.rest import ApiException


class TestLocale(unittest.TestCase):
    """Locale unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocale(self):
        """Test Locale"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.locale.Locale()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
