# coding: utf-8

"""
    Recomax REST API

    Recomax REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@recomax.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from .recommendation_api import RecommendationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRecommendationApi(unittest.TestCase):
    """RecommendationApi unit test stubs"""

    def setUp(self):
        self.api = .recommendation_api.RecommendationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_query_item_using_get(self):
        """Test case for query_item_using_get

        Get Recommendations for items  # noqa: E501
        """
        pass

    def test_recommend_for_user_using_get(self):
        """Test case for recommend_for_user_using_get

        Get Recommendations for user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
