# coding: utf-8

"""
    Recomax REST API

    Recomax REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@recomax.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from .user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = .user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user_using_post(self):
        """Test case for add_user_using_post

        Add User  # noqa: E501
        """
        pass

    def test_add_user_using_put(self):
        """Test case for add_user_using_put

        Add User  # noqa: E501
        """
        pass

    def test_delete_user_using_delete(self):
        """Test case for delete_user_using_delete

        Delete User  # noqa: E501
        """
        pass

    def test_get_segments_using_get(self):
        """Test case for get_segments_using_get

        Get User List  # noqa: E501
        """
        pass

    def test_get_user_using_get(self):
        """Test case for get_user_using_get

        Get User  # noqa: E501
        """
        pass

    def test_list_users_using_get(self):
        """Test case for list_users_using_get

        List Users  # noqa: E501
        """
        pass

    def test_update_user_using_post(self):
        """Test case for update_user_using_post

        User item  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
