# coding: utf-8

"""
    Recomax REST API

    Recomax REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@recomax.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from .entity_tag import EntityTag  # noqa: E501
from swagger_client.rest import ApiException


class TestEntityTag(unittest.TestCase):
    """EntityTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityTag(self):
        """Test EntityTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.entity_tag.EntityTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
