# coding: utf-8

"""
    Recomax REST API

    Recomax REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@recomax.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from .attribute import Attribute  # noqa: E501
from swagger_client.rest import ApiException


class TestAttribute(unittest.TestCase):
    """Attribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttribute(self):
        """Test Attribute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.attribute.Attribute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
