# coding: utf-8

"""
    Recomax REST API

    Recomax REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@recomax.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from .response_entity import ResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestResponseEntity(unittest.TestCase):
    """ResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseEntity(self):
        """Test ResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.response_entity.ResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
