# coding: utf-8

"""
    Recomax REST API

    Recomax REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@recomax.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from .event_api import EventApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self):
        self.api = .event_api.EventApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_event_test_using_post(self):
        """Test case for create_event_test_using_post

        Get Event List  # noqa: E501
        """
        pass

    def test_create_event_using_put(self):
        """Test case for create_event_using_put

        Create event  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
